[package]
name = "sqlite-xl"
version = "0.0.1-alpha.3"
edition = "2021"

[dependencies]
sqlite-loadable = "0.0.6-alpha.6"
calamine = {version="0.23.1", features=["dates"]}
thiserror = "1.0"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[features]
static = ["sqlite-loadable/static"]
