name: "Test"
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  build-linux-x86_64-extension:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: make loadable
      - uses: actions/upload-artifact@v4
        with:
          name: sqlite-xl-linux-x86_64-extension
          path: dist/*
  build-macos-x86_64-extension:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: make loadable
      - uses: actions/upload-artifact@v4
        with:
          name: sqlite-xl-macos-x86_64-extension
          path: dist/*
  build-macos-aarch64-extension:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: make loadable
      - uses: actions/upload-artifact@v4
        with:
          name: sqlite-xl-macos-aarch64-extension
          path: dist/*
  build-windows-x86_64-extension:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: make loadable
      - uses: actions/upload-artifact@v4
        with:
          name: sqlite-xl-windows-x86_64-extension
          path: dist/*